services:
  postgres:
    image: postgres:17.9
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: inventory
      POSTGRES_DB: inventory_service
    ports:
      - "5433:5432"
