spring.application.name=inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=inventory
spring.jpa.hibernate.ddl.auto=none
server.port=8083
