spring.application.name=gateway
server.port=9000
spring.security.oauth2.resourceserver.jwt.issuer-url=http://localhost:8181/realms/springboot-microservice-security-realm
#header authorization
spring.security.oauth2.resourceserver.jwt.issuer-uri-cert=http://localhost:8181/realms/springboot-microservice-security-realm/protocol/openid-connect/certs
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE